import { makeStyles } from '@material-ui/core';

const passwordPanelStyles = makeStyles((theme) => ({
  disciplineTitleStyle: {
    fontSize: '1rem',
    lineHeight: '1rem',
    fontWeight: '400',
    letterSpacing: '-0.2px',
    marginBottom: '1.5rem',
  },
  disciplineStyle: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  keywordStyle: {
    backgroundColor: 'var(--teal-primary)',
    color: 'var(--white)',
    fontSize: '0.875rem',
    lineHeight: '1rem',
    letterSpacing: '-0.2px',
    fontFamily: 'Poppins',
    fontWeight: '400',
    borderRadius: '1rem',
    padding: '0.5rem 0.75rem',
    marginRight: '1rem',
    marginBottom: '2.5rem',
    '&:hover, &:focus': {
      backgroundColor: 'var(--teal-primary)',
    },
    '& > span': {
      padding: '0',
    },
    '& > svg': {
      color: 'var(--white)',
      width: '0.875rem',
      height: '0.875rem',
      marginLeft: '0.5rem',
      marginRight: '0',
    },
    '& > svg:hover': {
      color: 'var(--util-red-300)',
      backgroundColor: 'var(--white)',
      borderRadius: '2px',
    },
  },
  addKeywordStyle: {
    border: '1px solid var(--teal-primary)',
    backgroundColor: 'var(--white)',
    color: 'var(--teal-primary)',
    fontFamily: 'Poppins',
    fontSize: '0.875rem',
    lineHeight: '1rem',
    letterSpacing: '-0.2px',
    fontWeight: '400',
    borderRadius: '1rem',
    padding: '8px 12px',
    marginRight: '1rem',
    marginBottom: '40px',
    cursor: 'pointer',
    '& > span': {
      padding: '0',
    },
    '& > svg': {
      color: 'var(--teal-primary) !important',
      width: '1rem !important',
      height: '1rem !important',
      marginLeft: '0 !important',
      marginRight: '10px !important',
    },
  },
  modalTitle: {
    padding: '0',
    '& h2': {
      fontFamily: 'Montserrat',
      fontWeight: '400',
      fontSize: '1.125rem',
      lineHeight: '1rem',
      letterSpacing: '-0.2px',
      color: 'var(--teal-primary)',
      padding: '1.25rem 1.25rem 0',
    },
  },
  modalContent: {
    display: 'flex',
    padding: '1.25rem',
    '& > p': {
      fontSize: '14px',
      lineHeight: '1.25rem',
      fontWeight: '400',
      fontFamily: 'Poppins',
      color: 'var(--text-normal)',
      margin: '0px',
    },
  },
  modalAction: {
    padding: '0 1.25rem 1rem',
  },
  chipIcon: {
    marginTop: 'auto',
  },
  chipStyle: {
    paddingLeft: '2px',
    '& > div': {
      marginBottom: '0px',
    },
    '& input': {
      fontSize: '0.875rem',
      lineHeight: '1rem',
      fontFamily: 'Poppins',
      fontWeight: '400',
      marginLeft: '0.5rem',
    },
    '& input::placeholder': {
      color: 'var(--text-normal)',
      fontFamily: 'Poppins',
      fontSize: '0.75rem',
      lineHeight: '1rem',
      letterSpacing: '-0.2px',
    },
    '& > div:before, & > div:after': {
      borderBottom: '1px solid rgba(29, 32, 32, 0.1) !important',
    },
    '& > div:after': {
      transform: 'scaleX(0) !important',
    },
  },
  chipAddItemStyle: {
    backgroundColor: '#EDF5F6',
    padding: '0.5rem 0.75rem',
    marginBottom: '0.5rem',
    marginLeft: '0.5rem',
    '& > span': {
      padding: '0 0.5rem 0 0',
      fontSize: '0.875rem',
      lineHeight: '1rem',
      fontFamily: 'Poppins',
      fontWeight: '400',
      letterSpacing: '-0.2px',
      height: '1rem',
    },
    '& > svg': {
      margin: '0',
      width: '1rem',
      height: '1rem',
      color: 'var(--teal-primary)',
    },
  },
  deleteKeywordButton: {
    backgroundColor: 'var(--util-red-300) !important',
    padding: '0.625rem 1rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: '500',
    fontFamily: 'Poppins',
    color: 'var(--white)',
    borderRadius: '10px',
    textTransform: 'none',
    letterSpacing: '-0.2px',
    '& svg': {
      color: 'var(--white)',
      width: '1rem',
      height: '1rem',
      marginRight: '0.5rem',
    },
    '&:hover': {
      backgroundColor: 'var(--util-red-500) !important',
    },
  },
  deleteCancelKeywordButton: {
    backgroundColor: 'var(--gray-normal) !important',
    marginLeft: '0.625rem !important',
    padding: '0.625rem 1rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: '600',
    fontFamily: 'Poppins',
    color: 'var(--white)',
    borderRadius: '10px',
    textTransform: 'none',
    letterSpacing: '-0.2px',
    '&:hover': {
      backgroundColor: 'var(--text-normal) !important',
    },
  },
  addKeywordButton: {
    backgroundColor: 'var(--util-orange-normal) !important',
    padding: '0.625rem 1rem',
    fontSize: '0.75rem',
    lineHeight: '1rem',
    fontWeight: '500',
    fontFamily: 'Poppins',
    color: 'var(--white)',
    borderRadius: '10px',
    letterSpacing: '-0.2px',
    textTransform: 'none',
    '& svg': {
      color: 'var(--white)',
      width: '1rem',
      height: '1rem',
      marginRight: '0.5rem',
    },
    '&:hover': {
      backgroundColor: 'var(--util-orange-dark) !important',
    },
  },
}));

export default passwordPanelStyles;
