import { makeStyles } from '@material-ui/core/styles';

export default makeStyles({
  textContainer: {
    position: 'relative',
    display: 'flex',
    textAlign: 'left',
  },
  longStringBlack: {
    background: 'var(--gray-dark)',
    boxShadow: '0px 1px 10px rgba(0, 0, 0, 0.1)',
    borderRadius: '2px',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '0.75rem',
    justifyContent: 'flex-start',
    whiteSpace: 'normal',
    lineHeight: '1rem',
    letterSpacing: '-0.2px',
    color: 'var(--white)',
    padding: '4px 8px',

    '&::after': {
      width: 0,
      position: 'absolute',
      height: 0,
      content: '""',
      borderLeft: '5px solid transparent',
      borderRight: '5px solid transparent',
      borderBottom: '5px solid var(--gray-dark)',
      bottom: '100%',
    },
  },
  longStringWhite: {
    background: 'var(--white)',
    position: 'absolute',
    boxShadow: '0px 1px 10px rgba(0, 0, 0, 0.1)',
    borderRadius: '2px',
    padding: '2px 4px',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: '0.6875rem',
    lineHeight: '1.25rem',
    letterSpacing: '-0.2px',
    color: 'var(--text-normal)',
    display: (props) => props.display,
    alignItems: 'center',
    justifyContent: 'flex-start',
    whiteSpace: 'normal',
    color: 'var(--white)',
    padding: '4px 8px',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    top: '100%',
    transform: 'translate(0, 5%)',
  },
});
