//AUTH AND DASHBOARD

export const DASHBOARD_RECENT_PROJECTS = 'DASHBOARD_RECENT_PROJECTS';
export const SET_AUTH_DETAILS = 'SET_AUTH_DETAILS ';
export const USER_PROFILE = 'USER_PROFILE';
export const SET_USER_ROLES = 'SET_USER_ROLES';
export const LOGOUT = 'LOGOUT';
export const USER_STATUS = 'USER_STATUS';
export const GET_USER_OVERVIEW = 'GET_USER_OVERVIEW';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

// NOTIFICATIONS

export const GET_MESSAGES = 'GET_MESSAGES';
export const READ_MESSAGE = 'READ_MESSAGE';
export const GET_SENDED_MESSAGES = 'GET_SENDED_MESSAGES';
export const GET_SENDED_MESSAGE_DETAIL = 'GET_SENDED_MESSAGE_DETAIL';
export const GET_RECEIVED_MESSAGE_DETAIL = 'GET_RECEIVED_MESSAGE_DETAIL';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const GET_MESSAGE_THREAD = 'GET_MESSAGE_THREAD';
export const SEND_MESSAGE = 'SEND_MESSAGE';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = ' CLEAR_NOTIFICATIONS';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

export const SEARCH_NOTIFICATIONS_AND_MESSAGES =
  'SEARCH_NOTIFICATIONS_AND_MESSAGES';
export const CLEAR_SENDED_MESSAGE = 'CLEAR_SENDED_MESSAGE';

export const GET_ONLY_PRIORITIES = 'GET_ONLY_PRIORITIES';
export const CLEAR_ONLY_PRIORITIES = 'CLEAR_ONLY_PRIORITIES';
export const CLEAR_TASKS_AND_FILES = 'CLEAR_TASKS_AND_FILES';

// TASKS
export const GET_PRIORITIES = 'GET_PRIORITIES';
export const SEARCH_FOR_TASKS = 'SEARCH_FOR_TASKS';
export const GET_TASKS_ASSIGNEES = 'GET_TASKS_ASSIGNEES';
export const CLEAR_FILTERED_TASKS = 'CLEAR_FILTERED_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_SUMMARY_TASK = 'UPDATE_SUMMARY_TASK';

// PROJECTS

export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECT = 'GET_PROJECT';
export const CLEAR_PROJECTS = 'CLEAR_PROJECTS';
export const CLEAR_PROJECT = 'CLEAR_PROJECT';
export const GET_PEOPLE = 'GET_PEOPLE';
export const GET_TEAMS = 'GET_TEAMS';
export const GET_LABELS = 'GET_LABELS';
export const CLEAR_LABELS = 'CLEAR_LABELS';
export const SEARCH_FOR_PROJECTS = 'SEARCH_FOR_PROJECTS';
export const GET_TEAM_PROFILES = 'GET_TEAM_PROFILES';
export const CLEAR_TEAM_MEMBERS = 'CLEAR_TEAM_MEMBERS';

// PROJECT FILES

export const SEARCH_FILES = 'SEARCH_FILES';
export const CLEAR_FILES = 'CLEAR_FILES';
export const GET_SINGLE_FILE = 'GET_SINGLE_FILE';
export const CLEAR_SINGLE_FILE = 'CLEAR_SINGLE_FILE';

// PEOPLE
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';
