import { makeStyles } from '@material-ui/core/styles';

const userStyles = makeStyles({
  userDetails: {
    background: 'var(--white)',
    width: 'max-content',
    borderRadius: '10px',
    boxShadow: '0px 4px 20px rgba(0, 0, 0, 0.05)',
    zIndex: 9999123,
    padding: '1.5rem 1.5rem 1.25rem 1.5rem',
    minWidth: '308px',
    height: 'auto',
    '&::after': {
      content: `" "`,
      width: '0',
      height: '0',
      borderLeft: '0.5rem solid transparent',
      borderRight: '0.5rem solid transparent',
      borderTop: '0.5rem solid var(--white)',
      position: 'absolute',
      bottom: '0',
      right: '50%',
      transform: 'translate(50%, 100%)',
    },
  },
  avatarWrapper: {
    width: '3.5rem',
    height: '3.5rem',
    borderRadius: '50%',
    marginRight: '1rem',
  },
  nameWrapper: {
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 600,
    height: '100%',
    fontSize: '1.5rem',
    order: (props) => props.border,
    color: 'var(--white)',
    background: (props) => props.background,
  },
  img: {
    borderRadius: '50%',
  },
  flexBoxCenter: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '1rem',
    justifyContent: 'space-between',
  },
  flexBox: {
    display: 'flex',
    alignItems: 'end',
    marginBottom: '0.25rem',
  },
  btnWrappper: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    marginLeft: '1.5rem',
  },
  name: {
    color: 'var(--teal-primary)',
    fontWeight: 500,
    marginBottom: '0.25rem',
    fontSize: '12px',
  },
  teamContainer: {
    display: 'flex',
    // alignItems: 'center',
    marginTop: '1rem',
  },
  teamWrapper: {
    borderRadius: '0.3125rem',
    width: '2rem',
    height: '2rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: '0.25rem',
  },
  teamName: {
    color: 'var(--white)',
    fontWeight: 600,
    fontSize: '12px',
  },
  title: {
    width: '3.5rem',
    fontWeight: 300,
    color: 'var(--text-darker)',
    textAlign: 'right',
    marginBottom: '0.25rem',
    marginRight: '1rem',
    textTransform: 'capitalize',
    fontSize: '12px',
  },
  loading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
    '& svg': {
      width: '2rem !important',
      height: '2rem !important',
    },
    '& *': {
      width: '2rem',
      fontSize: '2rem',
      height: '2rem',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
});

export default userStyles;
